"""aggiunti campi Serata

Revision ID: 934130262036
Revises: 379e1c24b0c3
Create Date: 2020-11-04 18:10:38.226175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934130262036'
down_revision = '379e1c24b0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serata', sa.Column('link_partecipazione', sa.String(length=255), nullable=True))
    op.add_column('serata', sa.Column('link_registrazione', sa.String(length=255), nullable=True))
    op.create_unique_constraint('constraint_serata', 'serata', ['id', 'data'])
    op.drop_constraint('contraint_serata', 'serata', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contraint_serata', 'serata', ['id', 'data'])
    op.drop_constraint('constraint_serata', 'serata', type_='unique')
    op.drop_column('serata', 'link_registrazione')
    op.drop_column('serata', 'link_partecipazione')
    # ### end Alembic commands ###
